server:
  port: 20570

spring:
  application.name: resource-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: angularpay
      username: service_account
      password: service_account_password
      authentication-database: angularpay

angularpay:
  pageSize: 10
  redis:
    host: localhost
    port: 6379
    timeout: 10000
